### ISSUE TITLE
Missing declarations / definitions as well as overlapping files from LBA1?

### ISSUE THREAD

**Issue by gtrainavicius** [2point21/lba2-classic#3]
Trying to compile the code, I noticed there's [`PERSO.C`](https://github.com/2point21/lba2-classic/blob/main/SOURCES/PERSO.C) file that seems to have come from [LBA1 `PERSO.C`](https://github.com/2point21/lba2-classic/blob/main/SOURCES/PERSO.C)

I assume that LBA2 should use PERSO.CPP instead, so PERSO.C shouldn't be there. There's a couple of other .C files with matching .CPP file, I didn't check them, but I suspect there could be more similar cases.

Furthermore, it looks like some declarations and definitions for some functions and variables are not anywhere in the source tree, for example:

* `DoAnimatedPolys`
* `Screen`
* `ScreenAux`
* `VueDistance`

Could it be that some headers (.H files) got overwritten from LBA1 or something? :)

Finally, I notice there's some references here and there to source files in `tools` folder that should be alongside LIB386 and SOURCES folders. (like [GETSRC.BAT](https://github.com/2point21/lba2-classic/blob/main/SOURCES/GETSRC.BAT)) - I wonder if the missing folder holds some important code for building LBA2.

**Comment by gtrainavicius** [comment]
Btw, this is how I'm attempting to build the source code:

1. I'm using [open-watcom-2_0-c-win-x64](https://github.com/open-watcom/open-watcom-v2/releases/tag/2021-10-02-Build)
2. I'd recommend checking out the sources into F:\PROJET\LBA2, as this seems to be the path that developers used, there's some hardcodings here and there. (Use `subst` to map F: to a folder on your PC and `mklink` can be used to make a symbolic link if you already have lba2-classic somewhere else and don't want to move :) )
3. In command prompt, run `call W:\watcom\owsetenv.bat`, then `set INCLUDE=%INCLUDE%;W:\lba2-classic\LIB386\H`
4. CD to W:\lba2-classic\SOURCE
5. Run `m`, or `m hd` which seems to disable some DEBUG defines which might make it easier to achieve a complete build for now.

Some changes I had to do to overcome first few errors:

* Comment out everything in GETSRC.bat (prepend `REM` to all lines)
* Change all occurrences of `binw` in watcom compiler path to `binnt64`, so it matches my host OS
* Rename PRINTTITRE.exe to something else, and place PRINTTITRE.bat in SOURCES folder with following contents:
    ```
    @echo.
    @echo Compiling %2
    @echo.
    ```
    (This just prints the currently compiled source file name, looks like the watcom compiler is not very verbose by default :) )
* Added `echo $(CC) $^& $(CFLAGS)` to `.c.obj` rule in Makefile so I can see the command line used.
* Similarly, `echo $(CP) $^& $(CFLAGS)` to `.cpp.obj` rule.
* In LIB386/H/SMACKER.H, comment out `#include     <SMACKER\SMACK.H>` (Some video library by RAD Game tools is not provided)
* In LIB386/H/SYSTEM.H, comment out `#include     <AIL\MSS.H>` (Miles sound system library by RAD tools is not provided)
* Add `typedef void *HSAMPLE;` anywhere in `LIB386/H/AIL/SAMPLE.H`
* Comment out `#include "F:\PROJET\LBA2\TOOLS\PERSO\3DEXT\EXTERN.H"` in SOURCES/defines.h
* Remove an invalid character at the end of `LIB386/H/SVGA/CLIP.H` file (it might not be visible in some editors, Notepad++ showed the unexpected symbol)

With all this done, the next compile errors I get after running `m hd`, I get:

```
C:\WORK\WATCOM\binnt64\wpp386 perso /hw /oneatxz /zp2 /5r /zq /s /w3 /bt=DOS /fh=f:lba.pch /DDOS4GW /DONE_GAME_DIRECTORY /d1 /DCDROM
perso.cpp(1): Warning! W701: col(17) pre-compiled header file being recreated ('BEZIER.H' has been modified)
BEZIER.H(31): Error! E498: col(61) syntax error before 'T_DECORS'; probable cause: incorrectly spelled type name
EXTFUNC.H(67): Error! E498: col(37) syntax error before 'xpmin'; probable cause: incorrectly spelled type name
perso.cpp(119): Error! E029: col(47) symbol 'ScreenAux' has not been declared
perso.cpp(920): Error! E029: col(60) symbol 'ScreenAux' has not been declared
perso.cpp(1445): Error! E029: col(44) symbol 'DISTANCE_VISEE' has not been declared
perso.cpp(1518): Error! E029: col(25) symbol 'DoAnimatedPolys' has not been declared
perso.cpp(1714): Error! E029: col(52) symbol 'DISTANCE_VISEE' has not been declared
perso.cpp(1731): Error! E029: col(41) symbol 'AlphaCam' has not been declared
perso.cpp(1732): Error! E029: col(41) symbol 'GammaCam' has not been declared
perso.cpp(1733): Error! E029: col(41) symbol 'VueDistance' has not been declared
perso.cpp(1831): Error! E029: col(44) symbol 'ScreenAux' has not been declared
W:\lba2-classic\LIB386\H\initadel.c(431): Error! E029: col(51) symbol 'ScreenAux' has not been declared
perso.cpp(2462): Error! E121: col(34) syntax error
perso.cpp(2463): Error! E029: col(14) symbol 'PtrPolySea' has not been declared
perso.cpp(2463): Error! E029: col(44) symbol 'MaxPolySea' has not been declared
Error(E42): Last command making (perso.obj) returned a bad status
Error(E02): Make execution terminated
```

Some of these errors can possibly be worked around by making some educated guesses, but it'd be a lot quicker if some previously missing or misplaced source files appeared. :)

**Comment by xesf** [comment]
Hi @gtrainavicius,
The missing files have been added so hopefully you can now compile the project.

Btw, you can submit changes to the community repo instead: https://github.com/2point21/lba2-classic-community
PR are welcomed!!

**Comment by gtrainavicius** [comment]
Ok, thank you, at least the first immediate errors got fixed, so closing this issue :)
