### ISSUE TITLE
Request: Time Commando and Alone in the Dark  game series engine source code release

### ISSUE THREAD

**Issue by J1Man** [2point21/lba2-classic#7]
Hello,

Thanks a lot for open sourcing the game engine codes of LBA1 and LBA2.

Is it possible to open source the game engine codes of Time Commando and Alone in the Dark game series?  Those were also exceptional games of their time.

Thanks.

**Comment by gwen-gg** [comment]
Hello @J1Man 
Yes it's planned for Time Commando
Alone in the Dark is not an IP we manage though, so it won't be something we do on our side !
